"use client";
import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getVehicleById, getVehicleDisplayName } from "@/data/vehicles";
import { useLanguage } from "@/components/LanguageProvider";
import { findObdCode } from "@/data/obd/codes";
import TechnicalReferenceList from "@/components/TechnicalReferenceList";

function ObdContent() {
  const router = useRouter(); const vehicleId = useSearchParams().get("vehicle"); const vehicle = getVehicleById(vehicleId); const { locale } = useLanguage(); const es = locale === "es";
  const [code, setCode] = useState("");
  const result = findObdCode(code);
  const c = es ? { back: "Volver", tag: "Diagnóstico OBD", title: "Lee códigos sin borrar evidencia", intro: "Los códigos orientan una revisión, pero no confirman por sí solos una pieza dañada.", before: "Antes de conectar", steps: ["Estaciona el vehículo de forma segura y consulta el manual para identificar el conector OBD.", "Usa un escáner compatible y registra los códigos, estado y síntomas.", "No borres códigos antes de anotarlos o compartirlos con un profesional."], warning: "No uses el escáner mientras conduces. Detente si existe una advertencia roja, humo o pérdida importante de potencia.", next: "Cuando tengas un código, regresa al diagnóstico y anótalo en tu solicitud de ayuda." } : { back: "Back", tag: "OBD diagnosis", title: "Read codes without clearing evidence", intro: "Codes can guide inspection, but they do not confirm a failed part by themselves.", before: "Before connecting", steps: ["Park safely and consult the manual to identify the OBD connector.", "Use a compatible scanner and record codes, status, and symptoms.", "Do not clear codes before recording them or sharing them with a professional."], warning: "Do not use the scanner while driving. Stop if there is a red warning, smoke, or major power loss.", next: "When you have a code, return to diagnosis and note it in your help request." };
  if (!vehicle) return null;
  return <main className="min-h-screen bg-slate-950 text-white"><section className="mx-auto max-w-3xl px-5 py-10 sm:px-8 sm:py-16"><button onClick={() => router.back()} className="text-sm text-slate-400">← {c.back}</button><p className="mt-8 text-sm font-bold text-sky-300">{c.tag}</p><h1 className="mt-2 text-4xl font-black">{getVehicleDisplayName(vehicle)}</h1><p className="mt-4 leading-7 text-slate-400">{c.intro}</p><div className="mt-8 rounded-3xl border border-sky-400/20 bg-slate-900 p-6"><label className="text-sm font-bold">{es ? "Consulta un código" : "Look up a code"}<input value={code} onChange={(event) => setCode(event.target.value)} placeholder="P0300" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 uppercase" /></label>{code && <div className="mt-4 rounded-2xl bg-slate-950 p-4">{result ? <><p className="font-black text-sky-300">{result.code} · {result.scope === "generic" ? (es ? "Genérico OBD-II" : "Generic OBD-II") : (es ? "Específico de fabricante" : "Manufacturer-specific")}</p><h2 className="mt-2 text-xl font-bold">{result.title[locale]}</h2><p className="mt-2 leading-7 text-slate-300">{result.description[locale]}</p></> : <p className="text-slate-400">{es ? "Aún no tenemos este código verificado en el catálogo. Regístralo sin borrarlo y consulta una fuente técnica del vehículo." : "This code is not yet verified in our catalog. Record it without clearing it and consult a vehicle-specific technical source."}</p>}</div>}</div><div className="mt-8 rounded-3xl border border-sky-400/20 bg-slate-900 p-6"><h2 className="text-xl font-bold">{c.before}</h2><ol className="mt-5 space-y-4">{c.steps.map((step, index) => <li key={step} className="flex gap-3"><span className="font-black text-sky-300">{index + 1}</span><span className="leading-7 text-slate-300">{step}</span></li>)}</ol></div><aside className="mt-6 rounded-2xl border border-amber-300/30 bg-amber-300/10 p-5 text-amber-100">⚠ {c.warning}</aside><p className="mt-6 text-sm leading-6 text-slate-400">{c.next}</p><TechnicalReferenceList vehicleId={vehicleId} topic="manual" /></section></main>;
}
export default function ObdPage() { return <Suspense fallback={null}><ObdContent /></Suspense>; }
